### ISSUE TITLE
dtheta renders as dth\eta

### ISSUE THREAD

**Issue by jolyonb** [asciimath/asciimathml#105]
Pretty much what it says in the title. Entering `dtheta`, which I expected would give me `d\theta` in LaTeX, instead gives `dth\eta`. Not sure why `\eta` has precedence over `\theta` in this situation!

I'm aware that I can instead write `d{::}theta`, but that shouldn't be necessary, right???

**Comment by davidfarmer** [comment]
I usually write it as d theta

But I agree it is not expected behavior.

Weirdly, dvartheta behaves as expected.

**Comment by saivan** [comment]
That could just be operator precedence right? `\eta` probably appears before `\theta`. So you could probably fix this by changing the order of the operators in the source; but could that have any unintended consequences?

**Comment by drlippman** [comment]
AsciiMath doesn't define or consider operator precedence.  It parses a string from left to right, looking for the largest symbol.

For dtheta, it starts at the left and finds the symbol `dt`.  From there it parses the remaining `heta`, doesn't find a symbol, so moves on and finds the symbol `eta`.  So your expression is actually parsing (correctly, based on the syntax) as `dt h eta`.

As David Farmer noted, the correct way to prevent matching symbols you don't want is to add spacing, so `d theta` works because it breaks apart the `dt` symbol.

**Comment by jolyonb** [comment]
Ah, didn't realize there was a `dt` symbol. That explains the behavior.
