### ISSUE TITLE
Row vectors in numerators don't display as vectors

### ISSUE THREAD

**Issue by jolyonb** [asciimath/asciimathml#113]
The vector `[[1, 2, 3]]` renders as a row vector, complete with square brackets. If you divide by anything though, those square brackets vanish: `[[1, 2, 3]]/2`. I'm not sure this is the intended behavior!

**Comment by drlippman** [comment]
This is not unexpected behavior, but certainly not desirable.  Normally Asciimath removes brackets around numerators and denominators, so that something like (x+4)/4 will display without parens in the numerator.  But that unwrapping is probably not desirable for matrices/vectors.

I'll make a fix so it skips the bracket removal for matrices.  

In the meantime, you can fix the display by adding an additional bracket around your numerator, like `([[1,2,3]])/2`
