### ISSUE TITLE
Incorrect transform of ]

### ISSUE THREAD

**Issue by scaljeri** [asciimath/asciimathml#37]
Consider the following AsciiMath formula

    ⟨text(-)2 , 4 ]

Now if I transform it as follows:

    AMTparseAMtoTeX('⟨text(-)2 , 4 ]')
    --> ⟨\text{-}{2},{4}{\]}

Now, the issue here is the `\]`, which should be (I think) just `]`. The problem is that MathJax renders the slash. Is this a transform issue ?

**Comment by drlippman** [comment]
Just so I can replicate it properly, what is the symbol you're putting before the text(-)?  It's not showing properly.

That said, the issue here is that the AMTgetTeXsymbol function assumes that every symbol should get backslashed unless it has the val property set.  It looks like some of the brackets need that property set.  I've never run into this because I usually have matched brackets, which get transformed into \left[ \right].  Whatever symbol you're using on the left must not be something the parser recognizes as a left bracket.

**Comment by scaljeri** [comment]
Here is more info on that first character: [latex demo](http://mathb.in/38943) [more info](http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=%E2%9F%A8&mode=char) or if the last link doesn't work here is the info on that site about that character:

Character	⟨
Character name	MATHEMATICAL LEFT ANGLE BRACKET
Hex code point	27E8
Decimal code point	10216
Hex UTF-8 bytes	E2 9F A8
Octal UTF-8 bytes	342 237 250
UTF-8 bytes as Latin-1 characters bytes	â <9F> ¨

According to the name it seems like some kind of bracket

**Comment by drlippman** [comment]
Ahh, yeah, AsciiMath doesn't understand Unicode characters for the most part.

AMTparseAMtoTeX("(:3,5]") would return "{\left\langle{3},{5}\right]}", which is probably the output you were wanting.

Even so, unmatched brackets should still be handled better.  I'll try to get that fixed.

**Comment by scaljeri** [comment]
Yep, that is the correct output. Thanks a lot!! Hope you have the time to work on this +1

**Comment by scaljeri** [comment]
I also found this one

    AMTparseAMtoTeX('[2,8rangle')
    --> "{\left[{2,8}\rightrangle}"

Which is incorrect, and should be

    "{\left[{2,8}\right\rangle}"

**Comment by drlippman** [comment]
Yup, somewhat related issue.  In that case, since the tex wasn't the symbol.input, then when the symbols get initialized the info needed for the AMTgetTeXbracket function gets lost.
It looks like I need to revamp that function to use the symbol.val attribute instead, make sure it gets copied over on the symbol initialization, and add the symbol.val attribute to the plain brackets as noted earlier.  I'll see if I can get that to work. 


     On Thursday, July 9, 2015 1:28 AM, Lucas Calje <notifications@github.com> wrote:
   

 I also found this oneAMTparseAMtoTeX('[2,8rangle')
--> "{\left[{2,8}\rightrangle}"
Which is incorrect, and should be"{\left[{2,8}\right\rangle}"

**Comment by scaljeri** [comment]
Also related

    'langletext(-)2 , 4 ]' --> {\leftlangle\text{-}{2},{4}\right]}

Any plans yet to fix this ? If not, and it is not too much work / complicated you can give me some hints were to like so I can fix this!

**Comment by drlippman** [comment]
Sorry it took me so long to get this fixed; I had it basically done several months ago but forgot to get it finalized and pushed out.
