### ISSUE TITLE
Alternative syntax for division.

### ISSUE THREAD

**Issue by AnthonyJacob** [asciimath/asciimathml#66]
I would like to use asciimath in my markdown document. The philosophy of markdown is to look in plain text as good as in formatted one.

Therefore it would be really nice, if there would be alternative to division syntax that looks more natural.

For example:

```
        a + b   
x[i] =  -----
          2
```

**Comment by dpvc** [comment]
While Markdown may have that philosophy, AsciiMath does not, and I suspect that the developer of the AsciiMath format would not be keen to support this approach, as it quickly gets very complicated (e.g., nested fractions), and would be subject to significant problems if you don't use a monospaced font.  It should also lead to requests for further 2-dimensional input, such as

```
      2
    x
```

or

```
      _______
    \/ x + 1
```

and other such things.  I don't see this format being very effective in the long run (at least not for anything but the simplest expressions).

In any case, you would need to make your request on the [AsciiMath](https://github.com/asciimath/asciimathml) project, since they are the ones that maintain the actual parsing of the format.

**Comment by drlippman** [comment]
Agreed. A format like this doesn't quite fit in the AsciiMath philosophy. It might be a good case for a new preprocessor script to convert this format into AsciiMath or TeX first.
